# Reference: https://build-cpp.github.io/cmkr/cmake-toml
# to build:
# > cmake -B build
# > cmake --build build --config Release
[project]
name = "hb_draw"

[target.imgui]
type = "interface"
sources = [
    "deps/imgui/*.cpp",
    "deps/imgui/backends/imgui_impl_dx12.cpp",
    "deps/imgui/backends/imgui_impl_win32.cpp"
]
include-directories = ["deps/imgui", "deps/imgui/backends"]

[target.sol2]
type = "interface"
include-directories = ["deps/sol2/include"]

[target.lua]
type = "static"
sources = ["deps/lua/*.c"]
include-directories = ["deps/lua"]

[target.glm]
type = "interface"
sources = ["deps/glm/glm/**.cpp"]
include-directories = ["deps/glm"]

[target.reframework]
type = "interface"
sources = ["deps/reframework/**.cpp"]
headers = ["deps/reframework/**.h", "deps/reframework/**.hpp"]
include-directories = ["deps/reframework"]

[target.hb_draw]
type = "shared"
sources = ["src/**.cpp"]
headers = ["src/**.hpp", "src/**.h"]
include-directories = ["src"]
link-libraries = [
    "lua",
    "sol2",
    "imgui",
    "glm",
    "d3d12",
    "reframework"
]
compile-features = ["cxx_std_20"]

cmake-after= """
set_target_properties(hb_draw PROPERTIES
                      RUNTIME_OUTPUT_DIRECTORY_RELEASE ../bin
)
"""
